## Descripción datos entrenamiento

In [1]:
import nibabel as nib
import numpy as np

peaks_img = nib.load('/home/riemann007/JupyterLab/Tesis/Proyecto/Datos/Entrenamiento/ISMRM Challenge 2022/ismrm2015_withReversed__peaks.nii.gz')
peaks = peaks_img.get_fdata()
print('peaks shape:', peaks.shape)       # e.g. (X,Y,Z,15)
print('peaks dtype:', peaks.dtype)
print('affine:\n', peaks_img.affine)
voxel_sizes = np.sqrt((peaks_img.affine[:3,:3] ** 2).sum(axis=0))
print('voxel sizes (mm):', voxel_sizes)

mask_img = nib.load('/home/riemann007/JupyterLab/Tesis/Proyecto/Datos/Entrenamiento/ISMRM Challenge 2022/ismrm2015_withReversed__local_seeding_mask.nii.gz')
print('mask shape:', mask_img.shape, 'unique values:', np.unique(mask_img.get_fdata())[:10])

# npz = np.load('/home/riemann007/JupyterLab/Tesis/Proyecto/Datos/Entrenamiento/Vecindades/data_100000_n3_k1.npz')
# inputs = npz['inputs']
# print('inputs shape:', inputs.shape)     # (N_samples, 408) esperado
# print('inputs dtype:', inputs.dtype)
# print('X mean len:', inputs.mean(axis=0).shape)  # debería ser (408,)


peaks shape: (138, 166, 134, 15)
peaks dtype: float64
affine:
 [[ -1.    0.    0.  -19.5]
 [  0.   -1.    0.  -21.5]
 [  0.    0.    1.    9.5]
 [  0.    0.    0.    1. ]]
voxel sizes (mm): [1. 1. 1.]
mask shape: (138, 166, 134) unique values: [0. 1.]


## Descripción datos validación

In [2]:
peaks_img = nib.load('/home/riemann007/JupyterLab/Tesis/MLP/Train_1/generated_peaks_csd.nii.gz')
peaks = peaks_img.get_fdata()
print('peaks shape:', peaks.shape)       # e.g. (X,Y,Z,15)
print('peaks dtype:', peaks.dtype)
print('affine:\n', peaks_img.affine)
voxel_sizes = np.sqrt((peaks_img.affine[:3,:3] ** 2).sum(axis=0))
print('voxel sizes (mm):', voxel_sizes)

mask_img = nib.load('/home/riemann007/JupyterLab/Tesis/seed_mask_validation.nii.gz')
print('mask shape:', mask_img.shape, 'unique values:', np.unique(mask_img.get_fdata())[:10])


peaks shape: (128, 128, 60, 15)
peaks dtype: float64
affine:
 [[  -2.            0.            0.          130.07400513]
 [   0.            2.            0.         -109.65599823]
 [   0.            0.            2.          -52.63299942]
 [   0.            0.            0.            1.        ]]
voxel sizes (mm): [2. 2. 2.]
mask shape: (128, 128, 60) unique values: [0. 1.]


## Dimensiones y valores únicos de las máscaras generadas

In [4]:
mask_img = nib.load('/home/riemann007/JupyterLab/Tesis/masks_validation/brain_mask.nii.gz')
print('mask shape:', mask_img.shape, 'unique values:', np.unique(mask_img.get_fdata())[:10])

mask_img = nib.load('/home/riemann007/JupyterLab/Tesis/masks_validation/deep_wm_mask_5mm.nii.gz')
print('mask shape:', mask_img.shape, 'unique values:', np.unique(mask_img.get_fdata())[:10])

mask_img = nib.load('/home/riemann007/JupyterLab/Tesis/masks_validation/fa.nii.gz')
print('mask shape:', mask_img.shape, 'unique values:', np.unique(mask_img.get_fdata())[:10])

mask_img = nib.load('/home/riemann007/JupyterLab/Tesis/masks_validation/wm_mask_fa0.22.nii.gz')
print('mask shape:', mask_img.shape, 'unique values:', np.unique(mask_img.get_fdata())[:10])

mask shape: (128, 128, 60) unique values: [0. 1.]
mask shape: (128, 128, 60) unique values: [0. 1.]
mask shape: (128, 128, 60) unique values: [0.         0.00463704 0.00617637 0.00639536 0.00642493 0.00672275
 0.00684353 0.00684511 0.00710638 0.00771162]
mask shape: (128, 128, 60) unique values: [0. 1.]


## Conteo de voxels para estimacion de numero de semillas posibles

In [5]:
root = '/home/riemann007/JupyterLab/Tesis/masks_validation'
mask_paths = [
    f"{root}/brain_mask.nii.gz",
    f"{root}/wm_mask_fa0.22.nii.gz",
    f"{root}/deep_wm_mask_5mm.nii.gz",
    '/home/riemann007/JupyterLab/Tesis/Proyecto/Datos/Entrenamiento/ISMRM Challenge 2022/ismrm2015_withReversed__local_seeding_mask.nii.gz'
]

for path in mask_paths:
    data = nib.load(path).get_fdata()
    count = np.count_nonzero(data)
    print(f"{path}: {count} voxeles")


/home/riemann007/JupyterLab/Tesis/masks_validation/brain_mask.nii.gz: 179398 voxeles
/home/riemann007/JupyterLab/Tesis/masks_validation/wm_mask_fa0.22.nii.gz: 58155 voxeles
/home/riemann007/JupyterLab/Tesis/masks_validation/deep_wm_mask_5mm.nii.gz: 9223 voxeles
/home/riemann007/JupyterLab/Tesis/Proyecto/Datos/Entrenamiento/ISMRM Challenge 2022/ismrm2015_withReversed__local_seeding_mask.nii.gz: 655251 voxeles
